name: CI Go Lab5

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Running integration test
        run: docker-compose -f docker-compose.yaml -f docker-compose.test.yaml up --exit-code-from test
      - name: Running unit test
        run: go test -v ./cmd/lb
